package com.devlaunch.entity;

import com.devlaunch.entity.enums.AttachmentCategory;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Represents a document attached to a job application.
 * <p>
 * Attachments (resume used, cover letter, offer letter, assessment PDF,
 * interview feedback) are stored on the local file system through the
 * attachment storage service; only the metadata is persisted here. The
 * stored file name is opaque and never exposed to the client.
 * </p>
 */
@Entity
@Table(name = "application_attachments")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString(callSuper = true, exclude = "application")
@EqualsAndHashCode(callSuper = true)
public class ApplicationAttachment extends BaseEntity {

    /**
     * The job application this attachment belongs to.
     * <p>
     * An application may have many attachments.
     * </p>
     */
    @NotNull(message = "Application is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "application_id", nullable = false)
    private JobApplication application;

    /**
     * The original file name as uploaded by the user.
     * <p>
     * Must not be blank.
     * </p>
     */
    @NotBlank(message = "File name is required")
    @Column(name = "file_name", nullable = false, length = 255)
    private String fileName;

    /**
     * The opaque name the file is stored under on disk.
     * <p>
     * Generated by the storage service and never exposed to the client.
     * </p>
     */
    @NotBlank(message = "Stored file name is required")
    @Column(name = "stored_file_name", nullable = false, length = 255)
    private String storedFileName;

    /**
     * The MIME content type of the file, if known.
     */
    @Column(name = "content_type", length = 100)
    private String contentType;

    /**
     * The file size in bytes.
     */
    @Column(name = "file_size")
    private Long fileSize;

    /**
     * The category of the attachment (resume, cover letter, offer letter,
     * assessment, interview feedback, or other).
     */
    @NotNull(message = "Attachment category is required")
    @Enumerated(EnumType.STRING)
    @Column(name = "category", nullable = false, length = 30)
    private AttachmentCategory category;

}
