-- DevLaunch interview question bank seed data.
--
-- Populates the interview_questions table with a starter set of questions
-- across all five interview categories. The seed is idempotent: INSERT
-- IGNORE skips any row whose (category, question) pair already exists, so
-- the file can safely run on every application startup. Expanding the bank
-- later only requires adding rows here or through the future admin module —
-- no backend code changes are needed.
--
-- Difficulty mix per category: 7 EASY / 7-8 MEDIUM / 5-6 HARD so a random
-- 3-4-3 interview selection is always satisfiable.

-- HR -----------------------------------------------------------------------
INSERT IGNORE INTO interview_questions (category, question, difficulty, created_at, updated_at) VALUES
('HR', 'Tell me about yourself and your background.', 'EASY', NOW(), NOW()),
('HR', 'What are your greatest strengths and weaknesses?', 'EASY', NOW(), NOW()),
('HR', 'Why do you want to work at this company?', 'EASY', NOW(), NOW()),
('HR', 'Where do you see yourself in five years?', 'EASY', NOW(), NOW()),
('HR', 'Tell me about a hobby or interest outside of work.', 'EASY', NOW(), NOW()),
('HR', 'What do you know about our company and its products?', 'EASY', NOW(), NOW()),
('HR', 'How do you prepare for an important meeting?', 'EASY', NOW(), NOW()),
('HR', 'Describe a time you faced a conflict with a teammate. How did you resolve it?', 'MEDIUM', NOW(), NOW()),
('HR', 'Tell me about a project you are proud of and your role in it.', 'MEDIUM', NOW(), NOW()),
('HR', 'How do you handle working under pressure or tight deadlines?', 'MEDIUM', NOW(), NOW()),
('HR', 'Describe a time you received constructive criticism and how you responded.', 'MEDIUM', NOW(), NOW()),
('HR', 'Why are you leaving your current job?', 'MEDIUM', NOW(), NOW()),
('HR', 'Tell me about a time you showed leadership.', 'MEDIUM', NOW(), NOW()),
('HR', 'How do you prioritise multiple competing tasks?', 'MEDIUM', NOW(), NOW()),
('HR', 'Describe a time you failed at something important. What did you learn?', 'HARD', NOW(), NOW()),
('HR', 'Tell me about a time you disagreed with your manager. How did you handle it?', 'HARD', NOW(), NOW()),
('HR', 'How would you handle a teammate who is not contributing their fair share?', 'HARD', NOW(), NOW()),
('HR', 'Describe a situation where you had to adapt to a significant change.', 'HARD', NOW(), NOW()),
('HR', 'What motivates you during long or repetitive work?', 'HARD', NOW(), NOW()),
('HR', 'Give an example of a time you went above and beyond your job description.', 'HARD', NOW(), NOW()),

-- HR (expanded bank: 30 EASY / 50 MEDIUM / 20 HARD) --------------------------
('HR', 'What are your short-term career goals?', 'EASY', NOW(), NOW()),
('HR', 'What is your educational background?', 'EASY', NOW(), NOW()),
('HR', 'What made you choose your field of study?', 'EASY', NOW(), NOW()),
('HR', 'What is your favourite subject and why?', 'EASY', NOW(), NOW()),
('HR', 'Describe your final year project in brief.', 'EASY', NOW(), NOW()),
('HR', 'What did you learn from your internship?', 'EASY', NOW(), NOW()),
('HR', 'How would you describe yourself in three words?', 'EASY', NOW(), NOW()),
('HR', 'What are you passionate about?', 'EASY', NOW(), NOW()),
('HR', 'What do you think makes a good team player?', 'EASY', NOW(), NOW()),
('HR', 'Do you prefer working in a team or working alone?', 'EASY', NOW(), NOW()),
('HR', 'How do you stay organised on a daily basis?', 'EASY', NOW(), NOW()),
('HR', 'What is your biggest strength as a fresher?', 'EASY', NOW(), NOW()),
('HR', 'What excites you about this role?', 'EASY', NOW(), NOW()),
('HR', 'How do you usually start your day?', 'EASY', NOW(), NOW()),
('HR', 'How do you keep your skills updated?', 'EASY', NOW(), NOW()),
('HR', 'Why did you choose software development as a career?', 'EASY', NOW(), NOW()),
('HR', 'Tell me about a college achievement you are proud of.', 'EASY', NOW(), NOW()),
('HR', 'How do you prefer to receive feedback?', 'EASY', NOW(), NOW()),
('HR', 'What kind of work environment suits you best?', 'EASY', NOW(), NOW()),
('HR', 'What is your dream job?', 'EASY', NOW(), NOW()),
('HR', 'Why should we hire you?', 'EASY', NOW(), NOW()),
('HR', 'What makes you a good fit for this team?', 'EASY', NOW(), NOW()),
('HR', 'Do you have any questions for us?', 'EASY', NOW(), NOW()),
('HR', 'Describe a time you showed teamwork to complete a task.', 'MEDIUM', NOW(), NOW()),
('HR', 'Tell me about a time you helped a struggling teammate.', 'MEDIUM', NOW(), NOW()),
('HR', 'Describe a time you had to explain a technical concept to a non-technical person.', 'MEDIUM', NOW(), NOW()),
('HR', 'How do you handle a missed deadline?', 'MEDIUM', NOW(), NOW()),
('HR', 'What would you do if you found a bug in your code after delivery?', 'MEDIUM', NOW(), NOW()),
('HR', 'Describe a time you took responsibility for a mistake.', 'MEDIUM', NOW(), NOW()),
('HR', 'Tell me about a time you had to learn a new skill quickly.', 'MEDIUM', NOW(), NOW()),
('HR', 'How do you decide what to work on first in the morning?', 'MEDIUM', NOW(), NOW()),
('HR', 'Describe a time you had to work with a difficult colleague.', 'MEDIUM', NOW(), NOW()),
('HR', 'How do you handle a situation where you disagree with your team decision?', 'MEDIUM', NOW(), NOW()),
('HR', 'Tell me about a time you had to present your work to an audience.', 'MEDIUM', NOW(), NOW()),
('HR', 'Describe a time you went out of your way to help a customer or user.', 'MEDIUM', NOW(), NOW()),
('HR', 'How do you handle feedback that you do not agree with?', 'MEDIUM', NOW(), NOW()),
('HR', 'Tell me about a time you had to make a decision with incomplete information.', 'MEDIUM', NOW(), NOW()),
('HR', 'How do you manage your time when multiple deadlines fall on the same day?', 'MEDIUM', NOW(), NOW()),
('HR', 'Describe a time you had to ask for help.', 'MEDIUM', NOW(), NOW()),
('HR', 'What would you do if your manager assigns you work outside your role?', 'MEDIUM', NOW(), NOW()),
('HR', 'Tell me about a time you improved a process at work or college.', 'MEDIUM', NOW(), NOW()),
('HR', 'How do you stay calm when things do not go as planned?', 'MEDIUM', NOW(), NOW()),
('HR', 'Describe a time you had to convince someone to accept your idea.', 'MEDIUM', NOW(), NOW()),
('HR', 'What is your approach to preparing for a job interview?', 'MEDIUM', NOW(), NOW()),
('HR', 'What do you think you can contribute to this company?', 'MEDIUM', NOW(), NOW()),
('HR', 'What makes our company different from its competitors?', 'MEDIUM', NOW(), NOW()),
('HR', 'What are your salary expectations?', 'MEDIUM', NOW(), NOW()),
('HR', 'Are you willing to relocate?', 'MEDIUM', NOW(), NOW()),
('HR', 'What are your plans for higher studies?', 'MEDIUM', NOW(), NOW()),
('HR', 'How do you handle a task that has no clear instructions?', 'MEDIUM', NOW(), NOW()),
('HR', 'Describe a time you received praise and what it meant to you.', 'MEDIUM', NOW(), NOW()),
('HR', 'Describe a time you had to reschedule or reprioritise your plan.', 'MEDIUM', NOW(), NOW()),
('HR', 'How do you maintain a healthy work-life balance?', 'MEDIUM', NOW(), NOW()),
('HR', 'Tell me about a time you had to manage your emotions in a professional situation.', 'MEDIUM', NOW(), NOW()),
('HR', 'How do you handle repetitive tasks without losing quality?', 'MEDIUM', NOW(), NOW()),
('HR', 'Tell me about a time you had to adapt your communication style.', 'MEDIUM', NOW(), NOW()),
('HR', 'How do you ensure every member of your team is heard?', 'MEDIUM', NOW(), NOW()),
('HR', 'Describe a time you made a mistake in front of others.', 'MEDIUM', NOW(), NOW()),
('HR', 'Describe a time you had to keep your team motivated during a challenging phase.', 'MEDIUM', NOW(), NOW()),
('HR', 'Tell me about a time you had to negotiate.', 'MEDIUM', NOW(), NOW()),
('HR', 'What does professionalism mean to you?', 'MEDIUM', NOW(), NOW()),
('HR', 'How do you handle a colleague who takes credit for your work?', 'MEDIUM', NOW(), NOW()),
('HR', 'Describe a time you had to work outside your comfort zone.', 'MEDIUM', NOW(), NOW()),
('HR', 'How do you react when your idea is rejected?', 'MEDIUM', NOW(), NOW()),
('HR', 'Tell me about a time you had to deliver bad news.', 'MEDIUM', NOW(), NOW()),
('HR', 'What do you think is the most important quality in a colleague?', 'MEDIUM', NOW(), NOW()),
('HR', 'Describe a time you had to make an unpopular decision.', 'HARD', NOW(), NOW()),
('HR', 'Tell me about a time you had to manage a conflict between two teammates.', 'HARD', NOW(), NOW()),
('HR', 'How would you handle a situation where your manager asks you to do something unethical?', 'HARD', NOW(), NOW()),
('HR', 'Describe a time you had to deal with a very difficult customer.', 'HARD', NOW(), NOW()),
('HR', 'Tell me about a time you had to deliver a project that was falling behind.', 'HARD', NOW(), NOW()),
('HR', 'How do you handle being criticised publicly?', 'HARD', NOW(), NOW()),
('HR', 'Describe a time you had to choose between two equally important tasks.', 'HARD', NOW(), NOW()),
('HR', 'Tell me about a time you had to admit you were wrong.', 'HARD', NOW(), NOW()),
('HR', 'How do you handle a teammate who is being blamed unfairly?', 'HARD', NOW(), NOW()),
('HR', 'Describe a time you had to take a risk and it did not work out.', 'HARD', NOW(), NOW()),
('HR', 'How do you handle a situation where you disagree with company policy?', 'HARD', NOW(), NOW()),
('HR', 'Tell me about a time you had to manage up.', 'HARD', NOW(), NOW()),
('HR', 'Tell me about a time you had to deliver tough feedback to a teammate.', 'HARD', NOW(), NOW()),
('HR', 'How do you stay true to your values when under pressure?', 'HARD', NOW(), NOW());

-- Java ---------------------------------------------------------------------
INSERT IGNORE INTO interview_questions (category, question, difficulty, created_at, updated_at) VALUES
('JAVA', 'What is the difference between JDK, JRE, and JVM?', 'EASY', NOW(), NOW()),
('JAVA', 'What are the primitive data types in Java?', 'EASY', NOW(), NOW()),
('JAVA', 'What is the difference between == and equals() in Java?', 'EASY', NOW(), NOW()),
('JAVA', 'Explain what a constructor is in Java.', 'EASY', NOW(), NOW()),
('JAVA', 'What is the difference between a class and an object?', 'EASY', NOW(), NOW()),
('JAVA', 'What is method overloading in Java?', 'EASY', NOW(), NOW()),
('JAVA', 'What is the difference between a Stack and a Queue?', 'EASY', NOW(), NOW()),
('JAVA', 'Explain the difference between an abstract class and an interface in Java.', 'MEDIUM', NOW(), NOW()),
('JAVA', 'Explain the difference between HashMap and ConcurrentHashMap.', 'MEDIUM', NOW(), NOW()),
('JAVA', 'Explain how Garbage Collection works in Java.', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is the difference between checked and unchecked exceptions?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'Explain the difference between method overloading and method overriding.', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is the difference between ArrayList and LinkedList?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'Explain the equals() and hashCode() contract in Java.', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is the difference between a Set and a List?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'How does the JVM split memory between the stack and the heap, and what causes an OutOfMemoryError?', 'HARD', NOW(), NOW()),
('JAVA', 'Explain how string immutability and the string pool work in Java.', 'HARD', NOW(), NOW()),
('JAVA', 'What are Java streams and how do they differ from collections?', 'HARD', NOW(), NOW()),
('JAVA', 'Explain the difference between synchronized, volatile, and atomic variables.', 'HARD', NOW(), NOW()),
('JAVA', 'How does the Java memory model affect visibility between threads?', 'HARD', NOW(), NOW()),

-- Java (expanded bank: 30 EASY / 50 MEDIUM / 20 HARD) -----------------------
('JAVA', 'What is Java and why is it called a platform independent language?', 'EASY', NOW(), NOW()),
('JAVA', 'What is bytecode in Java and how is it generated?', 'EASY', NOW(), NOW()),
('JAVA', 'What are the different types of operators available in Java?', 'EASY', NOW(), NOW()),
('JAVA', 'Explain type casting in Java. What is the difference between implicit and explicit casting?', 'EASY', NOW(), NOW()),
('JAVA', 'What are wrapper classes in Java and why are they needed?', 'EASY', NOW(), NOW()),
('JAVA', 'What is autoboxing and unboxing in Java?', 'EASY', NOW(), NOW()),
('JAVA', 'What is the difference between String, StringBuilder, and StringBuffer?', 'EASY', NOW(), NOW()),
('JAVA', 'How do you reverse a String in Java without using the reverse method?', 'EASY', NOW(), NOW()),
('JAVA', 'What is an array in Java and how do you declare and initialize one?', 'EASY', NOW(), NOW()),
('JAVA', 'What are the components of a method signature in Java?', 'EASY', NOW(), NOW()),
('JAVA', 'What is the difference between instance variables and static variables?', 'EASY', NOW(), NOW()),
('JAVA', 'What is a package in Java and why do we use packages?', 'EASY', NOW(), NOW()),
('JAVA', 'What is encapsulation in Java and how is it achieved?', 'EASY', NOW(), NOW()),
('JAVA', 'What is abstraction in Java?', 'EASY', NOW(), NOW()),
('JAVA', 'What is inheritance in Java and what are its types?', 'EASY', NOW(), NOW()),
('JAVA', 'What is polymorphism in Java and what are its two types?', 'EASY', NOW(), NOW()),
('JAVA', 'What is the purpose of the toString method in Java?', 'EASY', NOW(), NOW()),
('JAVA', 'What is an interface in Java?', 'EASY', NOW(), NOW()),
('JAVA', 'What is the difference between break and continue statements in Java?', 'EASY', NOW(), NOW()),
('JAVA', 'What is the ternary operator in Java and when would you use it?', 'EASY', NOW(), NOW()),
('JAVA', 'What is the difference between public, private, and protected access modifiers?', 'EASY', NOW(), NOW()),
('JAVA', 'What is the this keyword in Java and how is it used?', 'EASY', NOW(), NOW()),
('JAVA', 'What is the difference between throw and throws in Java?', 'EASY', NOW(), NOW()),
('JAVA', 'How does HashMap work internally in Java?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is the difference between HashMap and Hashtable in Java?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is the difference between HashMap and TreeMap in Java?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is the difference between LinkedHashMap and HashMap in Java?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is a HashSet in Java and how does it store unique elements?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is a PriorityQueue in Java and when would you use it?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is the difference between Comparable and Comparator in Java?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'How do you sort a list of custom objects in Java?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is an Iterator in Java and what are its key methods?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is a ConcurrentModificationException and when does it occur?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is the difference between fail-fast and fail-safe iterators in Java?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is the difference between Collection and Collections in Java?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is the difference between an Error and an Exception in Java?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'How do you create a custom exception in Java?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is try-with-resources in Java and how does it work?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is a lambda expression in Java 8?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is a functional interface in Java 8 and what are some built-in examples?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is a method reference in Java 8 and what are its types?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is the Optional class in Java 8 and what are its benefits?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is the difference between intermediate and terminal operations in Java streams?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is the difference between map and flatMap in Java streams?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is a Thread in Java and what are the ways to create one?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is the difference between a Thread and a Runnable in Java?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is synchronization in Java and why is it important?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is a deadlock in Java and what are the ways to avoid it?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is a race condition in multithreading and how do you prevent it?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is the difference between sleep() and wait() in Java?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is an ExecutorService in Java and what are its benefits?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is the difference between Callable and Runnable in Java?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is a Future in Java and how is it used with Callable?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is the Object class in Java and what methods does it provide?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is the difference between final, finally, and finalize in Java?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is the super keyword in Java and how is it used?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is serialization in Java and how is it implemented?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is the transient keyword in Java and when is it used?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is reflection in Java and what are its use cases?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What are generics in Java and what are their benefits?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What are annotations in Java and how are they used?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'You are designing a banking application. Which collection would you use to store daily transactions and why?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'How do you count the frequency of each character in a string in Java?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is the output of the following code? int a = 5; System.out.println(a++ + ++a);', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is the diamond operator in Java and why was it introduced?', 'MEDIUM', NOW(), NOW()),
('JAVA', 'What is a memory leak in Java and how can you prevent it?', 'HARD', NOW(), NOW()),
('JAVA', 'What is the difference between minor GC and major GC in the JVM?', 'HARD', NOW(), NOW()),
('JAVA', 'Explain the difference between weak, soft, and phantom references in Java.', 'HARD', NOW(), NOW()),
('JAVA', 'What is a ThreadLocal variable and when would you use it in Java?', 'HARD', NOW(), NOW()),
('JAVA', 'What is the difference between ReentrantLock and the synchronized keyword in Java?', 'HARD', NOW(), NOW()),
('JAVA', 'What is a CountDownLatch and how is it different from a CyclicBarrier?', 'HARD', NOW(), NOW()),
('JAVA', 'What is the producer-consumer problem and how do you solve it using Java concurrency?', 'HARD', NOW(), NOW()),
('JAVA', 'How does ThreadPoolExecutor work internally in Java?', 'HARD', NOW(), NOW()),
('JAVA', 'What is the difference between a Future and a CompletableFuture in Java?', 'HARD', NOW(), NOW()),
('JAVA', 'What is type erasure in generics and what problems does it cause?', 'HARD', NOW(), NOW()),
('JAVA', 'What is the diamond problem in Java and how is it resolved?', 'HARD', NOW(), NOW()),
('JAVA', 'How do you create an immutable class in Java and why would you do so?', 'HARD', NOW(), NOW()),
('JAVA', 'What is the difference between synchronized collections and concurrent collections in Java?', 'HARD', NOW(), NOW()),
('JAVA', 'What is a virtual thread in Java and how does it differ from a platform thread?', 'HARD', NOW(), NOW()),
('JAVA', 'What is the difference between the extends and super wildcards in Java generics?', 'HARD', NOW(), NOW());

-- Spring Boot ---------------------------------------------------------------
INSERT IGNORE INTO interview_questions (category, question, difficulty, created_at, updated_at) VALUES
('SPRING_BOOT', 'What is Spring Boot and what are its main advantages?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between @RestController and @Controller?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What is dependency injection and how does Spring implement it?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What is the purpose of the application.yml file?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What does @SpringBootApplication do?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'Explain the difference between @Component, @Service, and @Repository.', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What is an annotation in Spring? Give an example.', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What is Spring Boot auto-configuration and how does it work?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'How would you secure a REST API with Spring Security?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between @Autowired and constructor injection?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between @RequestMapping and @GetMapping?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the Spring IoC container and what is a bean?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between a controller and a service class?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the role of Spring Data JPA repositories?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'Explain the Spring bean lifecycle and the available bean scopes.', 'HARD', NOW(), NOW()),
('SPRING_BOOT', 'What is @Transactional and how does transaction propagation work?', 'HARD', NOW(), NOW()),
('SPRING_BOOT', 'Explain how the Spring Security filter chain works with JWT authentication.', 'HARD', NOW(), NOW()),
('SPRING_BOOT', 'How do you avoid N+1 queries with Spring Data JPA?', 'HARD', NOW(), NOW()),
('SPRING_BOOT', 'How does @ControllerAdvice centralise exception handling?', 'HARD', NOW(), NOW()),
('SPRING_BOOT', 'What are circular dependencies in Spring and how do you resolve them?', 'HARD', NOW(), NOW()),

-- Spring Boot (expanded bank: 30 EASY / 50 MEDIUM / 20 HARD) -----------------
('SPRING_BOOT', 'What is the Spring Framework and how does Spring Boot build on top of it?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between @Component and @Bean in Spring?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What is component scanning in Spring Boot and how does it work?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What are Spring Boot starter dependencies and why are they useful?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between application.properties and application.yml?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What are Spring profiles and when would you use them?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What is Spring Boot DevTools and what does it do?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What is the default port of a Spring Boot application and how can you change it?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What is the purpose of @PathVariable in a REST controller?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What is the purpose of @RequestParam in a REST controller?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between GET and POST requests in REST?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between PUT and PATCH in a REST API?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What is a JPA entity and how is it defined?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between @Entity and @Table annotations?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What is CrudRepository in Spring Data JPA and what methods does it provide?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What is the @Value annotation used for in Spring?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What is the purpose of @Configuration in Spring?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between @GetMapping and @PostMapping?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What is CORS and why is it needed in a Spring Boot application?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What is ResponseEntity and how is it used?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What does the spring-boot-starter-web dependency include?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What does SpringApplication.run() do in a Spring Boot application?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'What is the purpose of the @Transactional annotation?', 'EASY', NOW(), NOW()),
('SPRING_BOOT', 'How does Spring resolve dependencies when multiple beans of the same type exist?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between @Primary and @Qualifier?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between constructor injection and setter injection?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the purpose of @Bean methods in a @Configuration class?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between eager and lazy bean initialization in Spring?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'How do you override a Spring Boot auto-configuration?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between @EnableAutoConfiguration and @SpringBootApplication?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between @ConfigurationProperties and @Value?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'How do you use environment variables in a Spring Boot application?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between @Valid and @Validated?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'How do you handle validation errors in a Spring Boot REST API?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'How do you return a custom HTTP status code from a REST controller?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between @ResponseStatus and ResponseEntity?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'How do you handle file uploads in a Spring Boot application?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between an interceptor and a filter in Spring?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'How do you configure CORS globally in a Spring Boot application?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'How does Spring Data JPA generate queries from method names?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between a derived query and a @Query annotation?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is JPQL and how is it different from native SQL?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'How do you implement pagination in Spring Data JPA?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'How do you sort query results in Spring Data JPA?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between LAZY and EAGER fetching in JPA?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What are cascade types in JPA and when should you use them?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'How do you define a OneToMany relationship in JPA?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between a unidirectional and bidirectional relationship in JPA?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is a native query in Spring Data JPA and when would you use it?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'How do you hash passwords in Spring Security?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between authentication and authorization?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is a UserDetailsService and what is its role in Spring Security?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the purpose of a SecurityFilterChain bean in Spring Security?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between JWT and session-based authentication?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is CSRF and when should you disable it in a REST API?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between @PreAuthorize and @Secured?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'How do you configure method-level security in Spring Security?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What are the transaction isolation levels in Spring?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What happens when an exception is thrown inside a @Transactional method?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between @ControllerAdvice and @ExceptionHandler?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'How do you create a custom exception in Spring Boot and handle it globally?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'How do you test a Spring Boot controller with MockMvc?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between @WebMvcTest and @SpringBootTest?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between @MockBean and @Mock in tests?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the purpose of @DataJpaTest?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between a monolith and a microservices architecture?', 'MEDIUM', NOW(), NOW()),
('SPRING_BOOT', 'How do you implement caching in Spring Boot with @Cacheable?', 'HARD', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between pessimistic and optimistic locking in JPA?', 'HARD', NOW(), NOW()),
('SPRING_BOOT', 'How does Spring AOP work under the hood for @Transactional?', 'HARD', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between JDK dynamic proxy and CGLIB proxy in Spring?', 'HARD', NOW(), NOW()),
('SPRING_BOOT', 'How do you implement refresh tokens with JWT in Spring Security?', 'HARD', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between OAuth2 and JWT-based security?', 'HARD', NOW(), NOW()),
('SPRING_BOOT', 'How do you containerise a Spring Boot application with Docker?', 'HARD', NOW(), NOW()),
('SPRING_BOOT', 'What is the Saga pattern and how does it work?', 'HARD', NOW(), NOW()),
('SPRING_BOOT', 'What is the role of a service registry such as Eureka in microservices?', 'HARD', NOW(), NOW()),
('SPRING_BOOT', 'How does Spring Cloud Config Server centralize configuration across microservices?', 'HARD', NOW(), NOW()),
('SPRING_BOOT', 'What is the role of an API gateway in a microservices architecture?', 'HARD', NOW(), NOW()),
('SPRING_BOOT', 'How do you secure microservice-to-microservice communication?', 'HARD', NOW(), NOW()),
('SPRING_BOOT', 'What is the difference between a fat jar and a war in Spring Boot?', 'HARD', NOW(), NOW()),
('SPRING_BOOT', 'How do you handle database migrations in a Spring Boot application?', 'HARD', NOW(), NOW());

-- SQL ----------------------------------------------------------------------
INSERT IGNORE INTO interview_questions (category, question, difficulty, created_at, updated_at) VALUES
('SQL', 'Explain the difference between INNER JOIN and LEFT JOIN.', 'EASY', NOW(), NOW()),
('SQL', 'What is a primary key?', 'EASY', NOW(), NOW()),
('SQL', 'What is the difference between DELETE and TRUNCATE?', 'EASY', NOW(), NOW()),
('SQL', 'Explain the difference between WHERE and HAVING.', 'EASY', NOW(), NOW()),
('SQL', 'What is a foreign key and why is it used?', 'EASY', NOW(), NOW()),
('SQL', 'What is the difference between a table and a view?', 'EASY', NOW(), NOW()),
('SQL', 'What does SELECT DISTINCT do?', 'EASY', NOW(), NOW()),
('SQL', 'What is an index and when should you use one?', 'MEDIUM', NOW(), NOW()),
('SQL', 'Explain the difference between a primary key, a unique key, and a foreign key.', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is the difference between GROUP BY and ORDER BY?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is a subquery and when would you use one?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is the difference between UNION and UNION ALL?', 'MEDIUM', NOW(), NOW()),
('SQL', 'Explain the difference between INNER, LEFT, RIGHT, and FULL OUTER joins.', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is normalisation and why is it important?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is a transaction and what are the ACID properties?', 'HARD', NOW(), NOW()),
('SQL', 'Explain the difference between clustered and non-clustered indexes.', 'HARD', NOW(), NOW()),
('SQL', 'What is an execution plan and how can it help optimise a query?', 'HARD', NOW(), NOW()),
('SQL', 'Explain the N+1 query problem and how to solve it.', 'HARD', NOW(), NOW()),
('SQL', 'What is a database deadlock and how do you prevent it?', 'HARD', NOW(), NOW()),
('SQL', 'Explain the difference between a correlated and a non-correlated subquery.', 'HARD', NOW(), NOW()),

-- SQL (expanded bank: 30 EASY / 50 MEDIUM / 20 HARD) -------------------------
('SQL', 'What is a database and what is a table in SQL?', 'EASY', NOW(), NOW()),
('SQL', 'What is the difference between a row and a column in a database table?', 'EASY', NOW(), NOW()),
('SQL', 'What is a candidate key and how does it differ from a primary key?', 'EASY', NOW(), NOW()),
('SQL', 'What is a composite key and when would you use one?', 'EASY', NOW(), NOW()),
('SQL', 'What is a unique key constraint and why is it used?', 'EASY', NOW(), NOW()),
('SQL', 'What are the different types of constraints in SQL?', 'EASY', NOW(), NOW()),
('SQL', 'What is NULL in SQL and how do you check for NULL values?', 'EASY', NOW(), NOW()),
('SQL', 'What is the basic syntax of a SELECT statement?', 'EASY', NOW(), NOW()),
('SQL', 'What does the INSERT statement do and what is its syntax?', 'EASY', NOW(), NOW()),
('SQL', 'What does the UPDATE statement do and what happens without a WHERE clause?', 'EASY', NOW(), NOW()),
('SQL', 'What does the DELETE statement do and what happens without a WHERE clause?', 'EASY', NOW(), NOW()),
('SQL', 'What is the purpose of the WHERE clause in a query?', 'EASY', NOW(), NOW()),
('SQL', 'How do you sort query results with ORDER BY in ascending and descending order?', 'EASY', NOW(), NOW()),
('SQL', 'What does the LIMIT clause do and when would you use it?', 'EASY', NOW(), NOW()),
('SQL', 'What is the difference between COUNT(*) and COUNT(column_name)?', 'EASY', NOW(), NOW()),
('SQL', 'What is the SUM function used for?', 'EASY', NOW(), NOW()),
('SQL', 'What is the AVG function and how is it used?', 'EASY', NOW(), NOW()),
('SQL', 'What are the MIN and MAX functions used for?', 'EASY', NOW(), NOW()),
('SQL', 'What is the difference between an aggregate function and a scalar function?', 'EASY', NOW(), NOW()),
('SQL', 'What is the CASE expression in SQL and how is it used?', 'EASY', NOW(), NOW()),
('SQL', 'What does the COALESCE function do in SQL?', 'EASY', NOW(), NOW()),
('SQL', 'What are common SQL data types for numbers and text?', 'EASY', NOW(), NOW()),
('SQL', 'What is the purpose of the AS alias keyword in SQL?', 'EASY', NOW(), NOW()),
('SQL', 'What is a SELF JOIN and when would you use it?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is a CROSS JOIN and what does it return?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is the difference between an implicit join and an explicit join?', 'MEDIUM', NOW(), NOW()),
('SQL', 'How do you write a query to find duplicate rows in a table?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is the difference between IN and EXISTS in SQL?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is the difference between ANY and ALL in SQL?', 'MEDIUM', NOW(), NOW()),
('SQL', 'How do you use aggregate functions with GROUP BY?', 'MEDIUM', NOW(), NOW()),
('SQL', 'How do you filter results after aggregation with HAVING?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What are common string functions in SQL and what do they do?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is the difference between LENGTH and CHAR_LENGTH?', 'MEDIUM', NOW(), NOW()),
('SQL', 'How do you concatenate strings in SQL?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What are common date functions in SQL?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is the difference between a subquery and a JOIN?', 'MEDIUM', NOW(), NOW()),
('SQL', 'How do you find the second highest salary in a table?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is the difference between IN and BETWEEN?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is the difference between NOT IN and NOT EXISTS?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is the LIKE operator and what are its wildcards?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What are window functions and how do they differ from aggregate functions?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is the ROW_NUMBER() function used for?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is the difference between RANK() and DENSE_RANK()?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What do the LEAD() and LAG() functions do?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is PARTITION BY in window functions and how does it work?', 'MEDIUM', NOW(), NOW()),
('SQL', 'How do you write a query to return the top N rows per group?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is a composite index and when is it useful?', 'MEDIUM', NOW(), NOW()),
('SQL', 'How do you create an index in SQL?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is the difference between an index scan and an index seek?', 'MEDIUM', NOW(), NOW()),
('SQL', 'How does an index improve query performance?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What are the downsides of creating too many indexes?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is the difference between COMMIT and ROLLBACK?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is a SAVEPOINT and how is it used?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What are the different transaction isolation levels?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is the difference between READ COMMITTED and REPEATABLE READ?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is the first normal form (1NF)?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is the second normal form (2NF)?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is the third normal form (3NF)?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is the difference between 3NF and BCNF?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is denormalisation and when would you use it?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is a stored procedure and what are its benefits?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is the difference between a stored procedure and a function?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is a trigger in SQL and when is it used?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is a CTE and how is it different from a subquery?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is a recursive CTE and how does it work?', 'MEDIUM', NOW(), NOW()),
('SQL', 'How do you avoid a full table scan in a query?', 'MEDIUM', NOW(), NOW()),
('SQL', 'What is the difference between a covering index and a regular index?', 'HARD', NOW(), NOW()),
('SQL', 'What is index fragmentation and how do you fix it?', 'HARD', NOW(), NOW()),
('SQL', 'What is the difference between a bitmap index and a B-tree index?', 'HARD', NOW(), NOW()),
('SQL', 'What is the difference between pessimistic and optimistic locking in databases?', 'HARD', NOW(), NOW()),
('SQL', 'What are dirty reads, non-repeatable reads, and phantom reads?', 'HARD', NOW(), NOW()),
('SQL', 'What is the difference between SERIALIZABLE and SNAPSHOT isolation?', 'HARD', NOW(), NOW()),
('SQL', 'How do you design a many-to-many relationship in a relational database?', 'HARD', NOW(), NOW()),
('SQL', 'What is an entity-relationship diagram and how is it used in database design?', 'HARD', NOW(), NOW()),
('SQL', 'How do you migrate data between databases safely?', 'HARD', NOW(), NOW()),
('SQL', 'What is the difference between vertical and horizontal scaling of a database?', 'HARD', NOW(), NOW()),
('SQL', 'What is database sharding and what are its challenges?', 'HARD', NOW(), NOW()),
('SQL', 'What is the difference between ETL and ELT?', 'HARD', NOW(), NOW()),
('SQL', 'What is the difference between OLTP and OLAP systems?', 'HARD', NOW(), NOW()),
('SQL', 'How do you implement pagination in SQL efficiently?', 'HARD', NOW(), NOW());

-- React --------------------------------------------------------------------
INSERT IGNORE INTO interview_questions (category, question, difficulty, created_at, updated_at) VALUES
('REACT', 'What is React and what are its core concepts?', 'EASY', NOW(), NOW()),
('REACT', 'Explain the difference between props and state in React.', 'EASY', NOW(), NOW()),
('REACT', 'What is JSX and how is it different from HTML?', 'EASY', NOW(), NOW()),
('REACT', 'What is a React component and what types exist?', 'EASY', NOW(), NOW()),
('REACT', 'What is the difference between a functional and a class component?', 'EASY', NOW(), NOW()),
('REACT', 'What does the useState hook do?', 'EASY', NOW(), NOW()),
('REACT', 'What is the purpose of the render method in React?', 'EASY', NOW(), NOW()),
('REACT', 'What are React hooks? Explain useState and useEffect.', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is the difference between controlled and uncontrolled components?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is the difference between useEffect and useLayoutEffect?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is the virtual DOM and how does React use it?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is the difference between useMemo and useCallback?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is a key in React lists and why is it important?', 'MEDIUM', NOW(), NOW()),
('REACT', 'How does React handle events?', 'MEDIUM', NOW(), NOW()),
('REACT', 'Explain the concept of the virtual DOM and reconciliation.', 'HARD', NOW(), NOW()),
('REACT', 'How does React handle performance optimisation?', 'HARD', NOW(), NOW()),
('REACT', 'Explain the rules of hooks and why they matter.', 'HARD', NOW(), NOW()),
('REACT', 'What is React context and when should you use it?', 'HARD', NOW(), NOW()),
('REACT', 'Explain how React batches state updates.', 'HARD', NOW(), NOW()),
('REACT', 'What is a higher-order component and when would you use one?', 'HARD', NOW(), NOW()),

-- React (expanded bank: 30 EASY / 50 MEDIUM / 20 HARD) ----------------------
('REACT', 'How do you pass data from a parent component to a child component?', 'EASY', NOW(), NOW()),
('REACT', 'What is conditional rendering in React and how is it implemented?', 'EASY', NOW(), NOW()),
('REACT', 'How do you render a list of items in React?', 'EASY', NOW(), NOW()),
('REACT', 'How do you attach an event handler to an element in React?', 'EASY', NOW(), NOW()),
('REACT', 'What is the children prop in React and when is it useful?', 'EASY', NOW(), NOW()),
('REACT', 'What is a fragment in React and why would you use it?', 'EASY', NOW(), NOW()),
('REACT', 'What is the difference between a React element and a React component?', 'EASY', NOW(), NOW()),
('REACT', 'What is the purpose of the className attribute in React?', 'EASY', NOW(), NOW()),
('REACT', 'What is the role of the App component in a React application?', 'EASY', NOW(), NOW()),
('REACT', 'What is npm and what is it used for in React development?', 'EASY', NOW(), NOW()),
('REACT', 'What is a production build in React and why is it important?', 'EASY', NOW(), NOW()),
('REACT', 'What is Vite and what is it used for in React projects?', 'EASY', NOW(), NOW()),
('REACT', 'What are environment variables in React and how do you access them?', 'EASY', NOW(), NOW()),
('REACT', 'What is the difference between a default export and a named export in React?', 'EASY', NOW(), NOW()),
('REACT', 'What is inline styling in React and when would you use it?', 'EASY', NOW(), NOW()),
('REACT', 'What is the spread operator and how is it used when passing props?', 'EASY', NOW(), NOW()),
('REACT', 'How do you update state in a functional component?', 'EASY', NOW(), NOW()),
('REACT', 'What is the initial value in useState and how do you set a default?', 'EASY', NOW(), NOW()),
('REACT', 'How do you pass a function as a prop to a child component?', 'EASY', NOW(), NOW()),
('REACT', 'What is conditional styling in React and how do you apply CSS classes conditionally?', 'EASY', NOW(), NOW()),
('REACT', 'What is the difference between text content and a JavaScript expression inside JSX?', 'EASY', NOW(), NOW()),
('REACT', 'What is ReactDOM and what does ReactDOM.createRoot() do?', 'EASY', NOW(), NOW()),
('REACT', 'What is the difference between a functional component and a plain function in JavaScript?', 'EASY', NOW(), NOW()),
('REACT', 'What is the useContext hook and how does it work?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is the useReducer hook and when would you use it instead of useState?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is the useRef hook and what are its common use cases?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is a custom hook in React and how do you create one?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is lifting state up in React and why is it useful?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is component composition in React and what are its benefits?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is prop drilling and what are the ways to avoid it?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is React.memo and when should you use it?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is the difference between React.memo and useMemo?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is lazy loading in React and how do you implement code splitting?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is React Suspense and what does it do?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What causes unnecessary re-renders in React and how do you prevent them?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is Zustand and how does it differ from Redux for state management?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is React Router and what are its main components?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is the difference between BrowserRouter and HashRouter?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is the purpose of the Routes component in React Router?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is the difference between Link and NavLink in React Router?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is the useNavigate hook and when would you use it?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is the useLocation hook and what information does it provide?', 'MEDIUM', NOW(), NOW()),
('REACT', 'How do you define and read route parameters in React Router?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is a controlled form in React and how do you manage its state?', 'MEDIUM', NOW(), NOW()),
('REACT', 'How do you validate form inputs in React?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is React Hook Form and what are its benefits?', 'MEDIUM', NOW(), NOW()),
('REACT', 'How do you handle form submission in React?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is Redux and what problem does it solve?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What are the core concepts of Redux: store, actions, and reducers?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is Redux Toolkit and how does it simplify Redux?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is the difference between Redux and the Context API?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is the difference between global state and local state in React?', 'MEDIUM', NOW(), NOW()),
('REACT', 'How do you fetch data from an API in React?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is the difference between fetch and axios in React?', 'MEDIUM', NOW(), NOW()),
('REACT', 'How do you handle loading states while fetching data in React?', 'MEDIUM', NOW(), NOW()),
('REACT', 'How do you handle errors when fetching data in React?', 'MEDIUM', NOW(), NOW()),
('REACT', 'How do you implement pagination when fetching data in React?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is the difference between async/await and .then() for API calls?', 'MEDIUM', NOW(), NOW()),
('REACT', 'How do you type props with an interface in React with TypeScript?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is the difference between a type alias and an interface in TypeScript?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is a generic component in React with TypeScript?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is React.FC and is it still recommended for typing components?', 'MEDIUM', NOW(), NOW()),
('REACT', 'How do you type event handlers in React with TypeScript?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is the useState functional update and when is it useful?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is the useEffect dependency array and how does it control execution?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is the cleanup function in useEffect and when is it needed?', 'MEDIUM', NOW(), NOW()),
('REACT', 'What is React Fiber and how does it enable concurrent rendering?', 'HARD', NOW(), NOW()),
('REACT', 'What is concurrent rendering in React 18 and what are its benefits?', 'HARD', NOW(), NOW()),
('REACT', 'What is the useTransition hook and when would you use it?', 'HARD', NOW(), NOW()),
('REACT', 'What is the useDeferredValue hook and how does it differ from useTransition?', 'HARD', NOW(), NOW()),
('REACT', 'What is an error boundary in React and how do you create one?', 'HARD', NOW(), NOW()),
('REACT', 'What is a React portal and when would you use it?', 'HARD', NOW(), NOW()),
('REACT', 'What is the render props pattern in React?', 'HARD', NOW(), NOW()),
('REACT', 'What are compound components and what problem do they solve?', 'HARD', NOW(), NOW()),
('REACT', 'What is the useImperativeHandle hook and how does it work with forwardRef?', 'HARD', NOW(), NOW()),
('REACT', 'How do you avoid stale closures in React hooks?', 'HARD', NOW(), NOW()),
('REACT', 'What is server-side rendering in React and what are its benefits?', 'HARD', NOW(), NOW()),
('REACT', 'What is the difference between server-side rendering and static site generation?', 'HARD', NOW(), NOW()),
('REACT', 'How do you optimize the initial load performance of a React application?', 'HARD', NOW(), NOW()),
('REACT', 'What is the difference between a Higher-Order Component and a custom hook?', 'HARD', NOW(), NOW());
